project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!scripts/"
  resources:
    - "files/**"
    - "images/**"
    - "publications/**/*.pdf"
    - "publications/**/*.html"
    - "publications/**/featured.*"
    - "posts/**/files/**"
    - "posts/**/featured.*"
    - "software/**/featured.*"
    - "software/**/files/**"
    - "software/**/*.js"

website:
  title: "Quentin André"
  favicon: images/favicon-qa.png
  google-analytics: "G-NJC77TQHY4"
  navbar:
    background: "transparent"
    foreground: "#565A5C"
    title: "Quentin André"
    left: []
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: publications/index.qmd
      - text: Blog Posts
        href: posts/index.qmd
      - text: Software
        href: software/index.qmd
      - text: CV
        href: files/vita.pdf
  page-footer:
    background: "transparent"
    foreground: "#565A5C"
    left: "&copy; 2026 Quentin André"
    center: "Made with [Quarto](https://quarto.org)"
    right:
      - icon: envelope
        href: mailto:quentin.andre@colorado.edu
        aria-label: Email
      - icon: twitter
        href: https://twitter.com/andre_quentin
        aria-label: Twitter
      - icon: google
        href: https://scholar.google.com/citations?user=FWaxM6MAAAAJ&hl=en
        aria-label: Google Scholar
      - icon: github
        href: https://github.com/QuentinAndre
        aria-label: GitHub

highlight-style: github

format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: []
    toc: true
    code-overflow: wrap
    include-after-body:
      file: scripts/merge-modified-date.html

filters:
  - scripts/dedupe-modified.lua
  - scripts/publication-body.lua

execute:
  freeze: true
